name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v1
    - name: install musl
      run: |
        rustup target add x86_64-unknown-linux-musl
        apt update && apt install -y musl-tools musl-dev
        update-ca-certificates
    - name: Build
      run: |
        cargo build --release --target x86_64-unknown-linux-musl
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: linux
        path: target/x86_64-unknown-linux-musl/release/simple_pixiv
